### ISSUE TITLE
high level design of model page, Variograms

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmmweb#17]
We're still finishing some small details on speed definition of outlier detection, but the app itself is working well now. We can update the speed definition anytime without much change on app.

Now I think it's time to start discuss on the model page. There could be at least some new points need to be considered on top of previous design:

- what kind of workflow do we want? 
   This is a top question because the dashboard structure is mainly linear. If we want to go back and forth in some steps then we need design very carefully. 
- the data may have one or more individuals. 
   How do we deal with this in modeling, reporting etc?
- do we need make plots in `ggplot` too?
   If the effort needed to make all kinds plot in `ggplot` is manageable, then it should worth the time. The plots in app will be more consistent, and we should have more control in all aspects of the plot, and can get higher quality plot outputs.

There are lots of [detailed issues recorded in the `project` page](https://github.com/ctmm-initiative/ctmm-webapp/projects/2), though the above 3 questions are more important.

**Comment by vestlink** [comment]
My suggestion is to keep plots to a minimum and only if they help guiding the user. I would stick to one plotting solutiong that best suits the app and user and not give the user too many options. It will just be confusing.

**Comment by vestlink** [comment]
I assume you have seen this https://github.com/daattali/shinyjs

**Comment by xhdong-umd** [comment]
@vestlink Yes I used `shinyjs` in my first RStudio addin. I actually try to avoid using it if not must, because I found sometimes it caused some problem.

I'm not sure about its usage in this topic, do you mean disable some elements with `shinyjs` when they are not needed?

As for app usage, I expect the final app to have some tooltips or hints, and user should go through some brief tutorials. There are some assumptions need to be conveyed to users. Once user knew about them, they should found them reasonable and easy to remember.

We are still focusing on basic features and design so the help part is not in priority now.

**Comment by xhdong-umd** [comment]
@jmcalabrese I saw you are not watching the project so maybe you didn't get notification unless was mentioned. What's your plan about the models page?

**Comment by chfleming** [comment]
The basic workflow of the package for model fitting is `ctmm.guess()` to generate a `GUESS` object (which has the same format as a ctmm fit object, but is used as the initial guess for numerical optimization), then `ctmm.select()` and then to look back at the results with a plot of the variogram and selected model.

With multiple animals, I have had many users do
```GUESS <- ctmm.guess(...,interactive=FALSE)```
to avoid hands on interaction with the (`variogram.fit()` called by `ctmm.guess()`) sliders.

As a blanket work flow, I would suggest 
* calculating the `variogram()`s (and at a later stage of development, expose the `dt` option to users)
* calculate the automated guesses from `ctmm.guess(...,interactive=FALSE)`. The only user choice here ATM is whether or not to turn on errors with `error=TRUE`. This is necessary with duplicate/near-duplicate times, but excessive for coarse data.
* Display the plots of the empirical variograms and initial guesses. Allow users to either move on to the model selection step or individually tweak the initial guesses as per `variogram.fit()`.
* select the models and plot variograms of the data (empirical variogram) and selected model.
* give the users the option to refit the data (using the new best fit instead of `GUESS`) to check convergence from `optim`.

**Comment by xhdong-umd** [comment]
I tried to write some functions for ggplot version plots. 

For location plot of `telemetry` object, we can have a function like `gplot(obj, subset = "all")`, which will draw a plot similar to the first overview plot in web app. The `subset` parameter can be a vector of identity index so you can choose to draw animal `3,4` with all data as background like `gplot(obj, c(3,4))`, and the color will be consistent with web app.

This is doable but I'm not sure if it's useful.  If you want more control of plot like point size, you will need more parameters which could be cumbersome. One advantage over basic plot is that you can launch a shiny app with your data for a zoomable plot like this:

```
# generate ggplot object
g <- gplot(buffalo, c(2,3))
# draw plot in console
g
source("/Users/xhdong/Projects/addin/gg_zoom/gg_zoom.R")
# launch a shiny app with zoomable plot
gg_zoom(g)
# another way of zoom using pipe
g %>% gg_zoom
```

For plots used in models, like variograms, I'm inclined to just use current plots. To implement them in ggplot seemed to need a lot of efforts, and there is not obvious advantages.

**Comment by xhdong-umd** [comment]
For variograms we may want to plot several variograms with different `fraction` values together, like a facet plot. It seemed that base plots need `par` to arrange plots in same page. 

I used `gridExtra` for similar task on `ggplot2` previously, and there is a `gridBase` package that place base plots in grid viewports, which is more flexible and powerful in arrangement. However there are still some limitations and mixing two plots system can have more difficulties, for example
- it may break once the window resized
- the output may not be saved

So it seemed that there are two approaches:
1. use base plots. This doesn't need any change on existing plots in modeling, though I'm not familiar with the base graphics system.
2. implement plots in modeling with `ggplot2`. It should be more powerful and flexible, but the efforts needed could be quite substantial, as I saw there are a lot of plots for different cases. And `ggplot2` definitely take some time to learn.

@chfleming , @jmcalabrese Do you have any plan about implementing plots in modeling with `ggplot2`? I think for current stage maybe we just use existing plots and make the app complete first, but in the future should we consider about this?

**Comment by chfleming** [comment]
I think base plot is perfectly fine for now.

If a zoom slider is going to be used across multiple individuals, I think instead of adjusting the fraction of the plot (which varies in scale by individual), it should adjust the range of the x-axis (lags), so to be universal across individuals. If you need code to do that on a logarithmic scale, just let me know. It would basically be like the current code, but using the smallest and largest (most extreme) non-zero lags of the population. With the x-axis fixed, using the same scale of y-axis across a population of the same species would then be possible/acceptable.

**Comment by jmcalabrese** [comment]
I agree with Chris that we should stick with base plots for now, and then once the workflow has been tested and refined, possibly add in ggplot2 graphics where appropriate.

I also agree that a facet-like plot where you can simultaneously zoom in/out on all the variograms that are displayed would be useful.

I can see advantages and disadvantages for both zooming by fraction, and for zooming by lag. E.g., sometimes I just want to quickly zoom into the short-lag portion of all variograms, and zooming by fraction is convenient for that. Other times, I want to look at all variograms simultaneously up to a given lag, and zooming by lag is great for that. If it's not too complicated to implement, perhaps a toggle switch that would let the user decide whether to zoom by fraction or zoom by lag would be the way to go?

**Comment by jmcalabrese** [comment]
After viewing the automated guesses against the empirical variograms, it would be cool if the user could click on a particular variogram where they were interested in fine-tuning the guess, and then that particular variogram would open in a new window or box with sliders like in variogram.fit(). Not sure if that is possible.

It might also be useful to have a tick box for each panel to turn on error in the GUESS object.

**Comment by xhdong-umd** [comment]
Previously we had an idea of generate multiple "snapshots" of variograms at different fraction values for same individual (kind of facet plot), because you can check all values with a zoom slider, but multiple snapshots at typical values can provide an overview in a glance. So the plan was to have multiple static variograms at different values plus one with zoom slider. At that time we haven't consider the possibility of processing multiple individuals at the same time.

Do we still need that "facet plots" of variogram for same individual?

**Comment by jmcalabrese** [comment]
I was talking about the case where you are simultaneously processing multiple individuals. If you are only working with one individual, then there would only be on panel in the plot, but you would still have the ability to zoom in/out with a slider.

I think having an overall zoom slider (whether by fraction or by lag) would scale much better to multiple individuals than having multiple static snapshots for each individual.

**Comment by chfleming** [comment]
I agree, especially considering that knowing the proper scale to zoom in on requires guessing at the model parameters... which is the purpose of checking this.

**Comment by xhdong-umd** [comment]
Yes, I just want to make sure that we don't want static snapshots anymore. So we will deal with multiple individuals at the same time by default.

**Comment by xhdong-umd** [comment]
@chfleming you mentioned about code that adjust the range of the x-axis (lags) in log scale. Can you put them here? We can use a range slider for this

<img width="281" alt="screen shot 2017-04-26 at 3 51 25 pm" src="https://cloud.githubusercontent.com/assets/25039897/25453798/47437248-2a98-11e7-9b51-146990ddb20e.png">

**Comment by vestlink** [comment]
i see the outlier issue is closed. however, I have a question. Suppose you want to use the outlier and want to "pull" the outlier in. Maybe you would think that it would be ok to place the point between the point before and after. Would that make sense?

**Comment by xhdong-umd** [comment]
@vestlink You can still comment in closed issue, or even reopen it if needed. For me "close an issue" just means it's no longer the active task. I copied your question to that issue and replied there. I also asked @chfleming 's opinion on this.

**Comment by xhdong-umd** [comment]
@chfleming What's the desired range of fraction if using a log slider? i.e. the min, max, default value of fraction.

<img width="726" alt="screen shot 2017-04-27 at 11 30 39 am" src="https://cloud.githubusercontent.com/assets/25039897/25491233/542961e8-2b3d-11e7-881d-ebc17109b27c.png">

The plot above is just showing the idea. There are several issues need to be addressed:
- ideally the figure size need to adjust based on individual count. What kind of aspect ratio do you want for individual variogram plot?
- the y axis is not fixed, Gabs is having different unit
- with slider label digits set as 2, the left end 0.001 value is not shown completely. If I use 3 digits, the slider is like this. Is this OK?

<img width="714" alt="screen shot 2017-04-27 at 11 38 38 am" src="https://cloud.githubusercontent.com/assets/25039897/25491499/27d7d29a-2b3e-11e7-9996-02793bb042a0.png">

**Comment by chfleming** [comment]
@xhdong-umd 
Instead of having 1 (relative) fraction for the entire group, I would target one (absolute) zoomed in scale for the entire group. Taking the code behind `variogram.fit`, with a list of variograms `SVFS` there would be some overarching code
```
# maximum lag over all variograms
max.lag <- sapply(SVFS, function(v){ last(v$lag) } )
max.lag <- max(max.lag)

# minimum lag>0 over all variograms
min.lag <- sapply(SVFS, function(v){ v$lag[2] } )
min.lag <- min(min.lag)

b <- 4 # arbitrary constant
min.step <- 10*min.lag/max.lag
```
and then for each individual in the list, the manipulate plot (I know this isn't Shiny code) would would look like
```
manipulate::manipulate( { plot.variogram(SVF[[i]][SVF[[i]]$lag<=b^(z-1)*max.lag,], fraction=1, ...) }, z=manipulate::slider(1+log(min.step,b),1,initial=1+log(fraction,b),label="zoom") )
```
subsetting each variogram by the same (exp/log) scale `b^(z-1)*max.lag` and plotting the whole (`fraction=1`) subset.

**Comment by xhdong-umd** [comment]
@chfleming Because @jmcalabrese mentioned that we could have both fraction and lag for zoom, I plan to have two tabs for them (they will be using different value and range, so reusing same slider with a switch will not work).

**Comment by chfleming** [comment]
@xhdong-umd The poorly named `min.step` is the minimum fraction, 1 is the maximum fraction and 1/2 is the default for the fraction, and then I just transformed that with the transformation between the slider variable and the fraction `fraction=b^(z-1)`.

**Comment by xhdong-umd** [comment]
I just updated the repo. The variograms with zoom for fraction is like this:

<img width="701" alt="screen shot 2017-04-27 at 3 11 02 pm" src="https://cloud.githubusercontent.com/assets/25039897/25500151/edc1d416-2b5b-11e7-96d2-63ca7dd31c04.png">

You can adjust the figure height and columns in panel. I will implement the zoom for lag in next step.

**Comment by chfleming** [comment]
I definitely don't think its necessary to fix the y-axis necessary on this tab with the fraction zoom, because the x-axis is is not fixed here. On the other tab with the lag zoom, that might be nice. I will make sure the `xlim` & `ylim` arguments behave correctly in `plot.variogram`.

**Comment by vestlink** [comment]
@xhdong-umd look at this solution (if you're not already familiar with it). https://www.exploratory.io/ i came across it a few days ago. They have done a lot of things right. I know that it is not a shiny app, but the work flow is nice.

**Comment by xhdong-umd** [comment]
@chfleming I was wondering if we need to fix y-axis **unit**. `Gabs` in this plot have different unit. I can't reproduce the result with new code, but I'm not sure if this will never happen again.

<img width="713" alt="screen shot 2017-04-27 at 11 30 46 am" src="https://cloud.githubusercontent.com/assets/25039897/25529377/bf48e202-2bef-11e7-859d-fdff9dc1965f.png">

@vestlink I didn't play with the exploratory software because it need at least a free trial to download. From the demo video it seemed to be html5/javascript on top of R. With html5/javascript as front end you can do anything you want in UI, so it's definitely flexible and powerful. Unfortunately that almost means implement Shiny (at least the UI part, I'm not sure whether they used Shiny or implemented R backend by themselves too), which need substantial resources in front end development and backend development.

I appreciate their UI design, but please allow me to cherrypicking some points. The demo video looks really nice, but the reality is probably not that smooth. 

- It give you an appearance of you can scrap any website by just pasting an URL, which is just illusion -- web scraping must be heavily customized for specific website, and keep updating to match any breaking change in that website, how can that be automatic and get clean result?

- The data mangling pipleline looks like you can just shuffle the steps and apply to new data. This actually require the user to know R, dplyr, tidy data, how to convert data between wide and long etc. You cannot just arrange the dplyr pipeline arbitrarily and expect it to work. Then if you are fluent with this, using menu to pick commands and form to fill out parameters are actually cumbersome. 

Basically I think it wrapped some simple commands in a nice UI, but that didn't lower the barrier of analysis that much.

Another powerful UI I liked is [H2O flow](http://blog.h2o.ai/2014/11/introducing-flow/), which has a flexible interface for H2O API. The UI is also built upon Javascript so they can do anything possible.

I think the things we did in this web app actually doesn't fit the exploratory workflow. Too many things are invented by ourselves for our own needs, which is quite different from the simple pipeline. I do often felt limited by Shiny, and really want something more flexible than the linear menu items, but we don't have resource to create html5/Javascript UI, at least not now.

**Comment by NoonanM** [comment]
@xhdong-umd I think it would be best to have consistent units across all plots. For some datasets, I've found ctmm returns different units between individuals, depending on inter-individual differences in ranging behaviour. That can make visual diagnostics challenging. Maybe the best option is to convert all plots to the most common unit across all individuals in the dataset?

**Comment by xhdong-umd** [comment]
The unit picking depend on the range of data. So there are two approaches:
- use the most common unit, though the plot above actually have 3 in `km2` and 3 in `hm2`.
- pick unit from the biggest range - or smallest range, depend on if you want `5, 10, 1000` or `0.2, 0.01, 1`.

**Comment by NoonanM** [comment]
Another approach might be to include two options: i) pretty units (the default output, which has the potential for differences between plots), and ii) SI units (m^2) for inter-plot comparisons.

**Comment by xhdong-umd** [comment]
I think the units need to be consistent. We can have a radio button to switch between SI units and a pretty units either in biggest range or smallest range, as SI units view can be useful sometimes.

**Comment by xhdong-umd** [comment]
I just updated the repo with the variograms zoomed by absolute lag.

<img width="704" alt="screen shot 2017-04-28 at 3 19 35 pm" src="https://cloud.githubusercontent.com/assets/25039897/25543858/2236dd20-2c26-11e7-9ce7-9ef862d60cc3.png">

I think it's safe to just use `0` as `min.lag`, right?

In the other hand, we could use a **range slider** that can define both left and right ends of a range of lag, but that seemed to unnecessary because I assume the part start from 0 is always wanted. 

I noticed that the plot by lag is significantly slower than plot by fraction. The only difference in code seemed to be the xlim parameter.

```r
fig_count <- 6
# by fraction
cell_count <- ifelse(fig_count %% 2 == 0, fig_count, fig_count + 1)
layout(matrix(1:cell_count, cell_count / 2, 2, byrow = TRUE))
lapply(selected, function(x) {
  plot(variogram(x), fraction = 0.5)
  title(x@info$identity)
})

# by lag
cell_count <- ifelse(fig_count %% 2 == 0, fig_count, fig_count + 1)
layout(matrix(1:cell_count, cell_count / 2, 2, byrow = TRUE))
lapply(selected, function(x) {
  plot(variogram(x), fraction = 1, 
       xlim = c(min.lag, max.lag))
  title(x@info$identity)
})

```

**Comment by xhdong-umd** [comment]
I looked the source code of `plot.variogram` about the units of y axis. With `ggplot2` you can change the plot unit with a scale function, but with base plot we may have to change `plot.variogram` and add a parameter to provide scale, like this

```r
plot.variogram <- function(x, CTMM=NULL, level=0.95, fraction=0.5, col="black", col.CTMM="red", xlim=NULL, ylim=NULL, SVF.scale=NULL, lag.scale=NULL,...)

if (is.null(SVF.scale)) {
  SVF.scale <- unit(max.SVF,"area")
}

```

**Comment by xhdong-umd** [comment]
I found my edit above on `plot.variogram` is not ideal. To calculate the unit outside the plot function, I still need to use the code similar to the part inside the plot function. It'll be better if we abstract the scale calculation into a function, then we can use that function to calculate the unit parameter.

I'm not sure if we should make so many changes just for adjusting units though. That being said, if we want to have an option to use SI units, we will also need some change to the plot function.

**Comment by chfleming** [comment]
On the master branch I've edited `plot.variogram` to

* respect `xlim` & `ylim` arguments
* subset the data according to `fraction || xlim` before plotting for speedup

It is correct that for variograms, `xlim` and `ylim` should both start with 0 for normal use.

I will now make an `extent` function for a list of variograms, and using that you can fix xlim & ylim across individuals easily.

**Comment by xhdong-umd** [comment]
Sorry I didn't think through about the subset for xlim. If some individual didn't have data in all the time range (for example only have data in 3 months while the xlim range is 4 months), this may result its plot having a shorter xlim, right?

From my previous test, `plot.variogram` worked with xlim, I'm not sure what need to be changed for this.

**Comment by chfleming** [comment]
I have pushed a variogram `extent` method that is documented. You can now subset what you want to plot, feed those variograms (in a list) to `extent`, and then it will give you back `xlim` and `ylim` values just like with the telemetry and UD extent methods, so that you can make tables of plots with the same scale that is chosen to be appropriate.

**Comment by jmcalabrese** [comment]
I agree with @NoonanM that consistent units should be maintained across different panels, and that there should be a choice between pretty or SI units. When the choice is pretty units, I think whatever pretty units the unit function returns for the majority of panels should be imposed on the other panels.

**Comment by xhdong-umd** [comment]
@chfleming Thanks for the update, the idea of using `extent` is great, with simplified and consistent usage. I think the slowness I talked must came from the mechanism of base plot updating xlim after the plot has been generated, so it's still the same speed even if you subset the data already. The fraction plot just draw each figure with subset data, which is quicker because there is no axis redraw from setting xlim.

I updated the repo, which used the new `extent` function so you will need the latest ctmm github version to run it.

Right now I just make all y axis to the max range in all individuals. This make the y axis comparable and with same unit. 

<img width="695" alt="screen shot 2017-05-01 at 10 01 05 am" src="https://cloud.githubusercontent.com/assets/25039897/25581375/6eeebe04-2e55-11e7-8680-65c3bbf2b227.png">

Compare to the screenshot above which have the y axis in different scale (even if the unit is same, the scale of y can be different). Do you think this approach is desirable? Should we use same y axis for the zoom by fraction plot too?

So if we decided to use same y axis across individuals, the unit will be consistent. However to switch it will need more change to the plot function, add units as parameters.

**Comment by NoonanM** [comment]
Just as a side thought, for first time users, or those unfamiliar with variogram analysis, it might be worth re-naming the tab 'Zoom by time-lag".

**Comment by chfleming** [comment]
I like how this looks for zoom by lag. I'm not a fan of zooming by fraction on multiple individuals, so I don't have a preference on what that should look like--@jmcalabrese

**Comment by xhdong-umd** [comment]
@NoonanM I think user may need a hint or help page to understand the meaning of x,y axes. But for the zooming itself, it's based on a percentage of time lag, so I'm hesitating to add too many information in the title.

Now I looked at the plots again, the two modes are actually both based on percentage of x axis, just the `zoom by lag` is the percentage of max x axis range applied to all individuals, `zoom by fraction` is the percentage of x axis for each individual itself. So they actually mean `zoom in same time lag range` and `zoom in relative percentage of time lag range`.

**Comment by xhdong-umd** [comment]
Since the two plots are very similar, and the slider value is both a percentage/fraction, we can actually combine them into one page, use a radio button to switch between absolute zoom and relative zoom.

**Comment by xhdong-umd** [comment]
Summary of questions need answer:
- any comment on naming of the plot, slider labels etc
- should we use same y axis range for relative fraction plot?
- is the log scale slider for absolute lag range optimal?
- to add a switch for SI units, we may need to add unit parameter to `plot.variogram` function.

**Comment by xhdong-umd** [comment]
@chfleming You mentioned that

> - calculate the automated guesses from ctmm.guess(...,interactive=FALSE). The only user choice here ATM is whether or not to turn on errors with error=TRUE. This is necessary with duplicate/near-duplicate times, but excessive for coarse data.

I assume the `error=TRUE` refer to the error slot in ctmm object. Do mean there should be a checkbox to turn on error? I didn't see error as a parameter for `variogram`  or `ctmm.guess`. How should I turn it on or off? Can it be used automatically based on if error info is available?

**Comment by xhdong-umd** [comment]
I updated the repo, now with a checkbox to overlay the fit from `ctmm.guess` on plot. 

<img width="715" alt="screen shot 2017-05-01 at 3 08 53 pm" src="https://cloud.githubusercontent.com/assets/25039897/25590865/2503ffae-2e80-11e7-9abf-45c002606581.png">

<img width="718" alt="screen shot 2017-05-01 at 3 09 02 pm" src="https://cloud.githubusercontent.com/assets/25039897/25590875/2928167e-2e80-11e7-8d53-f6bb78bcc330.png">

**Comment by xhdong-umd** [comment]
To switch on `error`, do have to fit model once without error, then enable error and fit 2nd time?

```r
# default model guess
GUESS <- ctmm.guess(DATA,interactive=FALSE)
# first fit without telemetry error
FITS <- list()
FITS$NOERR <- ctmm.fit(DATA,GUESS)
# second fit based on first with telemetry error
GUESS <- FITS$NOERR
GUESS$error <- TRUE
FITS$ERROR <- ctmm.fit(DATA,GUESS)
# model improvement
summary(FITS)
```

**Comment by chfleming** [comment]
1. The logarithmic scale is important to be able to work down to the short lags without excessive effort.
2. On the "Absolute range", it looks like the vertical extent isn't being recalculated when you zoom in.
3. If the data don't have tiny `diff(t)` then fitting first without error and second with error helps with speed and convergence of fitting. It is not necessary if the optimizer is working correctly. I would not worry too much about it, because the new optimizer that I have written is working very well and will not require this.

**Comment by xhdong-umd** [comment]
The y axis is updating with zoom now. I have to subset the data by xlim, then use extent to determine proper xlim ylim.

I have updated the repo. Note the "adjust guess parameters" has not been implemented yet.

**Comment by xhdong-umd** [comment]
I'm working on implementing the manual fit interface in Shiny. There are lots of coupled relations on units, model parameters so I want to be very careful.

@chfleming The variables `sigma` `tau1` etc inside the `manipulate::manipulate()` call refer to the slider value, even there are variables of same name outside the call (because R CHECK CRAN insisted on this?), right? 

[This line](https://github.com/ctmm-initiative/ctmm/blob/master/R/variogram.R#L1014) seems changed `tau1` slider value and `tau1` variable by `CTMM$range`. Does that mean the `tau1` slider can be removed if `CTMM$range` is `FALSE`? Similar thing happened on line 1020 too.

If I don't have the requirement to satisfy R CHECK CRAN, can I remove the declaration of these variables safely?

```r
z <- NULL
tau1 <- 1
tau2 <- 0
```

**Comment by chfleming** [comment]
@xhdong-umd Yes, all of those initial (useless?) declarations were to satisfy CRAN.

For your considerations, you can assume range=TRUE everywhere. What range=FALSE does is actually fix the first tau to Inf. But you can't do home-range estimation with those models and so I don't think they are worth including in the app.

Also, you can consider CPF=FALSE. I need to remove all of that code.

To summarize the code:
1. variogram.guess() does some simple calculations with the variograms and outputs initial parameter estimates.
2. The sliders then allow users to adjust these estimates (and activate error) in case varigoram.guess() did a bad job. Unit conversions are in place to make the slider values meaningful.
3. Manipulate doesn't allow me to change the slider limits on the fly, so if you run out of space, you can save the output and re-run with that output as the starting value. I don't know what options are available for you.

For future models, there is also some code in ctmm.guess() that estimates some other parameters from the data. Don't worry about that for now.

**Comment by xhdong-umd** [comment]
I have copied your code and modified it to Shiny version, now the slider is initialized correctly, I just need to made correct conversion for the slider value and feed them to the `CTMM` object.

By "change the slider limits on the fly", you mean after the initialization, you may still want to change them based on some user input (one slider limit depend on other input)? With Shiny you can change the value, min max etc when needed. I'm not sure when and how to change it though.

**Comment by chfleming** [comment]
Sometimes `variogram.guess` is so far off that the default slider max is insufficient. This is usually because of substantial telemetry error, which complicates the initial shape of the variogram.

It would be nice to either:
1. Be able to run a parameter to the end of a slider and have the slider max double automatically (perhaps on release of the mouse click).
2. Be able to click a button and have all slider maxima reset to twice the current parameter values.
whichever is easier to implement.

**Comment by jmcalabrese** [comment]
@xhdong-umd: I like the layout and functionality of the variogram page. I know @chfleming prefers zoom by lag to zoom by fraction, but I still find zoom by fraction superior for zooming in on small lag behavior of all plots simultaneously, and think we should keep both options. Switching between them with a radio button and using the same slider for both is a really clean and elegant solution. Very nice. The only usability issues that jumped out at me are that:

1) The individual plots are too compressed along the y-axis, and the aspect ratios are too extreme. I would suggest forcing a larger and more conventional aspect ratio, like golden ratio or similar.

2) The axis labels are too small on both axes, making the units hard to read.

**Comment by xhdong-umd** [comment]
I think keep them both have advantages, as the "relative zoom" can reveal more details for each plot. We just need to remind user that each figure have its own scale so it was meant to inspect plots individually, not for comparison.

There is a figure height input to control the height of individual plot. I guessed the current value is a little bit low, you can adjust the number and find a good range for you, then I can make it as default.

To control the aspect ratio directly would need to change the ylim, which also need to include the confidence interval (the gray area). If a bigger default figure height can make it work, I'd incline to not to change the ylim manually.

As for the axis labels, it looks good in individual plot but got compressed when we stack many plots in one panel. I'm adjusting some parameters for this now. The base plot need a lot of trial and error to find the right parameter combinations.

**Comment by xhdong-umd** [comment]
I updated the repo, with default figure height 250 pixels, and increased axes label size. Setting these parameters manually may have different effect in different platforms though. 

I also noticed the plot axis label become more detailed when the space increases.

<img width="699" alt="screen shot 2017-05-03 at 10 32 05 am" src="https://cloud.githubusercontent.com/assets/25039897/25665655/4713aa6e-2fec-11e7-9224-16d765c34c6c.png">

**Comment by xhdong-umd** [comment]
@chfleming With buffalo data, the tau velocity and error doesn't have effect on the fit, maybe it's because of the model? Should we disable the sliders if the model doesn't take the parameters?

**Comment by chfleming** [comment]
I have a bug in my code at the moment that the error parameter is not rendering without a fitted model (which includes uncertainty on the error). I'm fixing that right now.

tau velocity should be working, but you have to zoom way in to see it.

**Comment by xhdong-umd** [comment]
OK, I saw the effect of tau velocity. 

I've been thinking if we should make an interface with `variogram.fit` so it can be used in both manipulate and Shiny. Right now I copied the code in `variogram.fit` and made some changes for Shiny, then any update in `variogram.fit` need a revisit of these copied and changed code. I'm also not 100% sure if my version worked in all cases since I don't totally understand them.

To make an interface will need some substantial changes in structure:
- `init_sliders`, a function that generate information needed for slider initialization, which are slider labels, min, max, default value, unit etc.
- `variogram.fit.plot`, a generic function that will be used by both manipulate and Shiny, which took some input parameters and update the plot.
- `variogram.fit`, the manipulate version. It will call `init_sliders`, then build the manipulate sliders from the information, call `variogram.fit.plot` to plot the fit, transfer the manipulate sliders values to it as the input parameters.
- My shiny app will be using same functions, call `init_sliders` but build Shiny sliders, call `variogram.fit.plot` with the Shiny slider values. 

This way the Shiny app will always have same behavior with the manipulate version no matter what changes we will have.

Whether we should do this, or when should we do this depend on whether there could be more changes in this feature.

**Comment by chfleming** [comment]
The bug I fixed is in a different function, but that's a good idea.

`variogram.fit.plot` will have to take parameter arguments and `init_sliders` will have to be used to set parameter arguments. It looks like manipulate will accept variable name strings like `"x"=slider(...)` just as well as `x=slider(...)`. So we will also need a character array of parameter names. Will these 3 ingredients also be sufficient for Shiny? If so, I can try to make an abstraction layer within a couple of days.

**Comment by xhdong-umd** [comment]
`variogram.fit.plot` can take a list of some named values in SI units:  `zoom`, `sigma`, `tau1`, `tau2`, `circle`, `error`, and parameters `CTMM`, `variogram`. Inside the function it update `CTMM` with the values, draw the plot.

`variogram.fit` can convert the units before calling `variogram.fit.plot`, since it also called `init_sliders` already it has access to the units information. 

In my Shiny code I think I just wrote the slider id name manually. I have something like this:

```r
# init sliders
res <- list()
...
res$slider1 <- list(label = "zoom", 
                               min = 1+log(min.step,b), max = 1,
                               value = 1+log(fraction,b), step = 0.01)
...
res$slider2 <- list(label = label_2, min = 0, max = m*sigma,
                               value = sigma, step = 0.01)
...
# return other variables that could be of use
res <- c(res, list(variogram = variogram, CTMM = CTMM, 
                       b = b, sigma.unit = sigma.unit,
                       tau1.unit = tau1.unit, tau2.unit = tau2.unit))
return(res)
```

Then you can build manipulate sliders

```r
build_slider <- function(para_list) {
    return(manipulate::slider(para_list$min, para_list$max, initial=para_list$value,
label=para_list$label))
}

manlist <- list(zoom = build_slider(res$slider1),
                sigma = build_slider(res$slider2),
                        ...)
```

**Comment by xhdong-umd** [comment]
And I found [this discussion](http://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when) about satisfying R CRAN Check.

The two methods of 
- `if (getRversion() >= "2.15.1") globalVariables(c("x.values", "y.values"))` in a `zzz.R` file in `./R/.`
- `if (getRversion() >= "3.1.0") utils::suppressForeignCheck(c("x.values", "y.values"))`

are not perfect, but might be an alternative. Of course put all variables declarations in other places is not ideal, but at least the function itself is clean, and hopefully you don't have many variables need to be declared.

**Comment by xhdong-umd** [comment]
I updated the repo with the fine-tune fit feature. 

After you check the box of "guesstimate model" (do you have a better name for this?), choose the individual you would like to fine-tune in the drop down box. There will be a pop up for the manual fit.

The pop up is using 0.5 fraction, while the default page of absolute zoom is using a different fraction value(the slider is in 0.5 but that is the 50% of max x range of all figures), so the plot may look different. Switching to relative zoom will have a more comparable view.

You can edit in the drop down box directly. The pop up only happen when there is a change in drop down box. For example you chose Cilla, made some changes then closed the pop up window, then if you want to fine-tune Cilla again, you need to delete current input of Cilla then choose Cilla to activate the window. 

@chfleming The option of double range automatically when slider was dragged to the end may surprise users, so I will add a button to double the slider ranges. The `zoom` slider doesn't need adjustment, right?

<img width="951" alt="screen shot 2017-05-03 at 2 40 50 pm" src="https://cloud.githubusercontent.com/assets/25039897/25676606/a3a57e28-3010-11e7-928d-8986a814f722.png">

**Comment by xhdong-umd** [comment]
I updated repo with a slider to extend the slider ranges. You can increase the max limit of all the sliders except "zoom" to 0.5 ~ 10 times. If 10 is still not enough in some cases, we can chose another value.

**Comment by xhdong-umd** [comment]
I think the next steps are model selection and maybe turn on the `ERROR` for some data. 

- By using `ctmm.guess`, have we already selected some model and used it? 
- What's the proper model selection work flow? 
- Should we just use the best model by `ctmm.select`, or should we give more extensive options?

The model selection part may need some careful thinkings. I think I will start to look at the help and documentation of app because now seemed to be a good milestone point. Later if the interface in `variogram.fit` is finished I will also update the app to use the interface functions.

**Comment by jmcalabrese** [comment]
I like the updates to the variogram page. I also think having a "increase slider range" slider is a more intuitive solution than automagically doubling the range when the user hits a limit (some users may never discover that feature). 

A couple of usability observations:

1) Could we have log-scaled sliders that display the original values instead of logged values? So for fraction, instead of seeing a scale that goes from -3 to 0 with even spacing between steps, the user would see a scale that goes from 0.001 to 1 with log spacing between steps. I think that would be more intuitive for many users. Asking users to take antilogs in their head while they're working with various sliders is probably asking too much.

2) The differences between variograms with absolute zoom and scaling and variograms with relative zoom and scaling, both in terms of plot behavior and why the user would want each of them, are very similar to the differences between the facet and individual plots on the visualization page. With variograms, we are using radio buttons to switch between representations, but on the visualization page, we use different tabs. That seems inconsistent to me, and I wonder if users will find it confusing? I'm not sure which is the better solution at this point, but it seems like these kind of representation shifts should be kept consistent across the different pages of the webapp.

**Comment by jmcalabrese** [comment]
@xhdong-umd: I agree that focusing on help, documentation, clean-up and testing should be the priorities from now until the 15th. I would rather have the things that are already there working well and with documentation than trying to rush development of another layer of functionality.

**Comment by NoonanM** [comment]
@xhdong-umd @chfleming It regularly happens that some individuals in a dataset aren't range resident, and need to be excluded from the rest of the analyses. At the variogram stage, it would be useful (if possible) to have a tick box (or similar) where users can move through their data and select which animals are range resident (or vice versa, which animals aren't). Then, moving forward to the next stage of analysis, only individuals selected as range resident are carried forward.

**Comment by xhdong-umd** [comment]
I have some code that can convert the slider labels into log scale, so the underlying value is still the same, but the label and displayed values are in log scale. However it is in log base 10, and the current code in `variogram.fit` is in log base 4. 

@chfleming Do you want to keep it in base 4 or is it OK to change to base 10? I do notice that 0.5 is still 0.5 in log base 4, not sure if this is related.

As for the plots of 3.facet and 4.Individual, they are of same concept of absolute zoom and relative zoom. Though the facet plot keep all x axis aligned for easier comparison, so it's a single column layout. The individual plots have two sliders which will be useless in facet plot, and it's in 2 column layout to maximize the space usage. 

There is no tech difficulties to put two plots in same page with a radio button, but that will update and redraw the plot with every switch, compare to tabs which will have plot cached without redraw. The whole layout also changed dramatically in switch. In the variogram case the layout is almost identical, and the redraw is relative light (with bigger dataset the visualization plots could take a while to render).

So the concepts of plot design are quite similar, but from the UI perspective I think the different arrangements are better suited for their cases. We can convey the information of plot intentions and usage in the help document and video demo:
- plot 3 facet is scale fixed, position aligned for comparison. This doesn't have zoom.
- plot 4 individual is positioned freely for better visualize individuals with maximize space usage, still with scale fixed for comparison. The zoom can focus on the majority of each individual at the same time.
- variograms with absolute fraction zoom have same time lag range and scale. The zoom fraction is based on a portion of the individual with max time lag range in group, then applied to all individuals. Both X and Y are consistent for better comparison.
- variograms with relative zoom are independently zoomed into fraction of time lag for each. The scales are not fixed across individuals.

After the summary, I think the two cases are similar but with some differences. I tried to think some better names or labels to convey these differences, but found difficult to summary in a few words.

**Comment by xhdong-umd** [comment]
@NoonanM I need to think about that in the model selection context. It may involves selecting from multiple models for multiple individuals, so the workflow could be difficult to implement.

This will be the task in July, but my tentative idea is that the model fitting could take some time, so to deal with multiple individuals and multiple models, maybe we will have a "model fit planning" step, which is to create a recipe of fit which model with what parameters for each individual, then run the model fitting processes in batch. User can left the app running after he submitted the recipe.

**Comment by chfleming** [comment]
Instead of a slider to adjust the slider max, can we just have a button that sets all of the slider maxima to twice the current estimate, effectively centering all of the sliders. That would make the sliders easier to tweak, I think.

**Comment by xhdong-umd** [comment]
@chfleming At first I made a button, then I was afraid that doubling one time is not enough, so I wanted be able to continue expanding if needed. Because the first double took the initial slider limit, next double need to save previous states in some global variable. I don't like the global variable idea so changed it to slider instead.

By double the current estimate, you mean just use current slider value * 2 no matter what it is? So user can move to max, click button to double. Then he can move to max again, click button to double again. 

In the other hand it can also make the slider range smaller if the slider is on the left end. This could also be helpful to increase the slider resolution.

**Comment by chfleming** [comment]
This part with ctmm.guess (which includes within it variogram.fit and the sliders) is just for obtaining an initial guess. It is not really a fit or selected model and variogram.fit is a misnomer. It should be called variogram.eyeball.

The next step is to feed the data and initial guess into ctmm.select with verbose=TRUE, report the results, and take the best (first) model. Overfitting is not yet an issue with these starter models because they don't have anything interesting happening in the trend/mean term to overfit with.

The report should include both the summarized list of selected models and the plot of the best fit model atop the empirical variogram.

**Comment by chfleming** [comment]
The base I used is arbitrary, you can use whatever you like.

**Comment by chfleming** [comment]
Yes, I mean to set the slider max to equal twice the current slider value. This will help (1) both situations where you reach the slider max and want to go further and (2) situations where you are near the slider min and are having trouble with the resolution.

**Comment by xhdong-umd** [comment]
OK I will change the base and use a log slider. After you finish the interface on `variogram.fit` I'll update my code to make sure the app have same behavior with the manipulate version.

**Comment by jmcalabrese** [comment]
@xhdong-umd: 

1. Your justification for using a different UI for facet plots and multipanel variograms makes sense, and in light of that, I agree that we should keep those the way they are.

2. I just checked, and the variogram zoom slider still shows a log scale to the user, ranging from -3 to 0. Did you not have a chance to change the labels so that the user sees the original units on the slider, or was my comment unclear?

**Comment by xhdong-umd** [comment]
Interesting, I think I did push the changes to the repo. 

I just updated the repo again, and directly running from the repo showed this scale for me:

<img width="894" alt="screen shot 2017-05-09 at 9 26 35 am" src="https://cloud.githubusercontent.com/assets/25039897/25853147/be7f9b88-3499-11e7-871d-73620938635c.png">

Can you test again?

**Comment by jmcalabrese** [comment]
Ok, just tested again. 

On the main Visual diagnostics page (before selecting an individual to fine tune parameter guesses), I still see a slider range of -3 to 0. 

After selecting Cilla (with no outlier filtering or time subsetting), I see a zoom slider range of -1.547 to 1 on the slider palette. That seems like a mix of log scaling on the low end, and linear scaling on the high end. Not sure what's going on there, but that's not what I had in mind.

**Comment by xhdong-umd** [comment]
Shiny doesn't support log slider directly, so I used some javascript code to modify the slider labels. This could be some bug caused by different platform/browser interpreting that javascript code.

What platform/browser are you using?

**Comment by jmcalabrese** [comment]
I am on linux right now. I had been using Rstudio's built in browser window, and there the sliders are still as I described above. When opened in Firefox or Chromium, the slider range on the main Visual diagnostics page looks good: 0.001 to 1. The palette zoom slider then has range you showed above, but it seems like you multiplied the range by 10? Shouldn't it stop at 1 for maximum zoom?

**Comment by xhdong-umd** [comment]
The slider range in fine-tune window is same with the manipulate version of `variogram.fit`, which [calculated the range max as `1`](https://github.com/ctmm-initiative/ctmm/blob/dd1a6fb30019a6da8a0adf4a12f84a2f26124243/R/variogram.R#L955), then [converted the slider value](https://github.com/ctmm-initiative/ctmm/blob/dd1a6fb30019a6da8a0adf4a12f84a2f26124243/R/variogram.R#L1053) with `fraction <- b^(z-1)`, here `b` is the log base, `z` is the slider value, so this slider is not fraction, but a function of fraction. I want to keep the app behavior consistent with the manipulate version, so I used the same arrangement.

Now I just realized maybe manipulate doesn't support a log scale slider. So we may have to keep the manipulate version as is, and maybe use a different slider name to differentiate. We can use `fraction` instead of `zoom`.

**Comment by xhdong-umd** [comment]
@chfleming For our interface for `variogram.fit`, `variogram.fit.plot` should just take value of `fraction`, and it's the UI code's responsibility to convert between scales. So the manipulate version will generate the proper `fraction` value from the slider `zoom`, and the Shiny version will generate the proper `fraction` value from the log slider `fraction`.

If we can have the interface before the planned release (we can determine the date in next meeting), I'll update the code with the interface method. Otherwise I'll manually update the code first with current method.

**Comment by xhdong-umd** [comment]
I'll look at the linux RStudio browser and see if the slider problem can be fixed later.

**Comment by xhdong-umd** [comment]
I decided to stop on linux VM since it already took me one hour and I have not get R installed. I'll work on other issues first and check this later if have time. Before fixing the bug we will have to ask user to use firefox or chrome.

**Comment by vestlink** [comment]
maybe a warning when fitting the model saying something like "The model fitting may take some time..."

**Comment by xhdong-umd** [comment]
@vestlink There are notifications for all time consuming tasks. I also add a button initialize the model fitting explicitly, so it will not start after user switched page accidentally.

I planned to give user a summary of work plan before start fitting the models, and warn user about the plan that could take a long time to finish, like batch fitting many models.

**Comment by vestlink** [comment]
The "remove outlier" button seems a bit mis-placed when thinking about work flow.

I would consider moving it below the list ouf outliers listed considering that you would have to move back and forth too many times.

**Comment by xhdong-umd** [comment]
Do you mean moving the button from top of the table to bottom of the table like this?

<img width="697" alt="screen shot 2017-05-10 at 8 45 49 am" src="https://cloud.githubusercontent.com/assets/25039897/25899356/8defb434-355d-11e7-88bf-cb6d08d60fd7.png">

I put it on top because there are also a reminder for user about selecting rows, so it's natural to select rows, then remove them. If put the button to bottom, it will add one extra row to the box height. I also thought user need to inspect in the scatter plot before removal, so the screen focus is more likely to be on the upper part than the lower part.

**Comment by vestlink** [comment]
I see your point. Add long as it is described I  the work book to guide the
users or should be no problem

**Comment by xhdong-umd** [comment]
I changed the title to focus on variograms. The variograms feature is complete, so I'm closing this issue now.

When I need to work on models again, I'll create an new issue to continue the discussion on work flow.

**Comment by xhdong-umd** [comment]
@chfleming , I'm adding the switch of `ERROR` for vairogram. I didn't find any visual difference with `ERROR` on or off, is this normal?

```r
DATA <- as.telemetry(system.file("extdata","leroy.csv.gz",package="move"))
plot(variogram(DATA))
# default model guess
GUESS <- ctmm.guess(DATA,interactive=FALSE)
plot(variogram(DATA), CTMM = GUESS)
GUESS$error <- TRUE
plot(variogram(DATA), CTMM = GUESS)
```

Another question, will turning on `ERROR` change the error slider in the fine tune UI `variogram.fit`?

**Comment by xhdong-umd** [comment]
I also noticed you mentioned pooling variograms in the vignette. Do you think it worth to be added to the app? 

There could be a button that generate a popup window (or add another tab to the variogram box, that might be better since you can switch between two tabs easily), which pool all the individuals into one variogram. There can be a check list to select which individuals to be added/removed from the pool.

**Comment by chfleming** [comment]
I think the first options to throw in should be the `dt` option, and maybe `res` with that, for people with very irregular data.

For pooling, users will often want to select specific subsets of individuals with similar looking behavior. Sometimes that will be all individuals.

**Comment by xhdong-umd** [comment]
So you mean there should be the options of `dt`, `res`, `error` for variogram fitting? Using same options for all individuals is relative easy, but more cumbersome if you want to use different options for different individuals.

After pooling, how do we incorporate that pooled variogram into the general workflow, which usually involved separate result for each individual?

**Comment by chfleming** [comment]
The `dt` and `res` arguments are useful in calculating the variogram (before fitting) when people have irregular data. This would be for the optional `variogram` argument of `variogram.fit`/`ctmm.guess`'
For these options, I think its fair to have users group their data by sampling schedule, at least for the time being, if that makes your work easier.

Pooling is useful when individual data is sparse and individual variograms are noisy (less common than the above problem). At least procedurally, in this case you would want to use the pooled variogram for the (pooled) individuals just as you would have with their individual variogram. I suppose you just need to prevent people from re-pooling their variograms.

**Comment by xhdong-umd** [comment]
@chfleming @jmcalabrese I was going to move to model selection step then I saw `ERROR` option was mentioned before, so I thought I will just add it if it's simple. Now it seemed that `dt`, `res` and pooling will take some time to design and implement, for example
- how should we take input of `dt`? some text field with units, or should we provide the sampling interval of data for reference, or let use select from sampling intervals?
- we need some method to switch between pooled variogram and individual variogram. The current variogram plot is grouped base plot, which make annotation and modifying them a little bit awkward.

I think maybe I should first work on the next steps of model selection and home range estimation, and put these features on hold. There are only about 1 month left before the course, and we probably want the main features first.

**Comment by chfleming** [comment]
I would put model selection as a priority over variogram calculation options. Especially over pooling.

For `dt` I would use a drop-down box for units.

**Comment by jmcalabrese** [comment]
I agree with @chfleming about prioritizing model fitting/selection. I would prefer that the app has at least basic functionality all the way through AKDE by the animove course. We can worry about more advanced options once that's in place.

For dt, it might be useful to let the user visually select one or more values by clicking on a histogram of the sampling intervals in the data. In my experience, dt tends to be useful when that histogram is multimodal, and the user could just click on each of the modes, and the app would create a vector of the modal intervals in the background. Given the above, I would prefer to come back to this later after first completing the workflow through AKDE.

**Comment by jmcalabrese** [comment]
The pooled variogram only makes sense if you've got sparse data and individuals exhibit broadly similar movement behavior. If you're in that regime, then I think there are two scenarios where the pooled variogram could be useful : 1) you're interested in the variogram per se, and aren't going to go any further with the analyses, and 2) You want to get representative parameter guesses for model fitting and then impose those on all individuals that were in the pooled variogram.

One way to do it would be to let the user select which individuals to pool over, and then pooled variogram would be displayed along with the single individual variograms of any remaining individuals that were not selected to pool over. The guesstimate step would work the same, except that each individual in the pooled variogram would have the pooled variogram parameter guesses applied to it in the model fitting step.

The next question is how to activate the pooling functionality. One option would be to add a check box to the current variogram page, that when ticked opens up an interface to select individuals. Another way to do it would be to have a separate tab on the variogram page that would then have the required individual list to select from.

**Comment by xhdong-umd** [comment]
Thanks @jmcalabrese , with these detailed usage I can try to design easier to use UI and workflow. 

The variogram plots are difficult to add other UI elements as they are a single item of grouped base plots. I think I can make a table of individual names with same layout of variograms, then user can select individuals and pool them together. 

I'll put these in notes and work on model selection first.

**Comment by xhdong-umd** [comment]
@chfleming I'm working on the new `variogram.fit` code. The zoom slider used `1+log(fraction,b)` with `b=4` (probably because manipulate doesn't support log slider), but the shiny version is using log slider and base 10. To use the `variogram.fit.backend`, I need to convert the values for zoom slider back to log 10 first.

Can you add a parameter `b=4` to `variogram.fit.backend`(and remove`b<-4` in code)? That way I can use base 10, and your code don't need any other change.

I may have other suggestions while I'm working on it, so you don't need to change it now.

**Comment by xhdong-umd** [comment]
Why don't we just add a `name` to data frame instead of row.names? Of course there is no real difference between a name column and row.names, I'm just wondering.

**Comment by xhdong-umd** [comment]
I think `storer` is already in good shape. We need to transfer slider values to this function, and it's better to transfer explicitly. You will call it with manipulate sliders, and I will call it with shiny slider values, so I think the current format is optimal.

Though I think this line `fraction <- function(z=z) { b^(z-1) }` should be inside `variogram.fit` instead of backend, because shiny app will use a different base, and I don't have the `z-1` shift. This part should be manipulate specific instead of backend.

I'll propose a pull request when I finished.

**Comment by chfleming** [comment]
No particular reason for the row names instead of a "name" column.

The `fraction` function can be ignored by you for now, and I can move that code over.

The only thing I am unhappy with in `storer()` is that I couldn't figure out how to get it to work in manipulate without an explicit argument list.

**Comment by xhdong-umd** [comment]
I think an explicit argument list is unavoidable after the abstraction. manipulate works by substituting variables in first expression with control variables in 2nd expression, and update the 1st expression when the control variables (sliders etc) changed. Once we extract backend from manipulate code, `storer` have to take them from outside since they are not in the environment of backend function.

One problem I'm having is that some sliders are conditional(for example circle.period can be optional), but I need to transfer the slider values from shiny app to `storer` function. This means the parameters can have different combinations depend on the data.

**Comment by chfleming** [comment]
I'm not sure that I understand, but the `data.frame DF` should only specify parameters that need to be controlled, and others can be left `NULL` and aren't used. This is all determined by the structure of the `CTMM` object (fed through `vargiogram.guess`)

**Comment by xhdong-umd** [comment]
I will have some slider values like `input$tau1`, `input$circle_period` etc, and I need to transfer them in

```r
CTMM <- STUFF$storer(sigma = input$sigma,
    tau1 = input$tau1,
    tau2 = input$tau2,
    circle.period = input$circle_period,
    error = input$error)
```

However the `tau1` slider may not exist if `range == FALSE`, thus `input$tau1` will be NULL, and `storer` will get a NULL tau1 value.

**Comment by chfleming** [comment]
Yes, `NULL` assignments won't work, but their default values should be fine if nothing is passed.

I suppose it would be easier to have a list of all possible variable defaults. That way they could be assigned once, reassigned by manipulate/Shiny, and then fed into `storer`.

**Comment by xhdong-umd** [comment]
Yes, this is what I thought later. I think the defaults came from `backend` environment,  so it'll be easier to assign all variables to default value first inside `storer`(because `storer` have access to that environment), then take non-null values from parameter and override corresponding values.

I'll make a pull request for you to review if it worked.

**Comment by chfleming** [comment]
I'm thinking it will be easier to run `storer` within `do.call`, with a list of named parameter values taken from the manipulate/Shiny for arguments. That way the unused variables are automatically left at their default values and the code doesn't have to be updated if I add more parameters.

**Comment by xhdong-umd** [comment]
You are right, this should be a better approach.

**Comment by xhdong-umd** [comment]
I tried but cannot get it to work with manipulate. The manipulate expression is a special one, where we will use the slider variables but they don't have value yet. I tried this then there is error because the variable doesn't exist:

```r
  manipulate::manipulate(
    {
      # all sliders in data frame, except the zoom slider
      slider_names <- rownames(DF)
      slider_names <- slider_names[!(slider_names %in% "z")]
      slider_values <- lapply(slider_names, get)
      names(slider_values) <- rownames(DF)
      CTMM <- do.call(STUFF$storer, slider_values)

# Error in FUN(X[[i]], ...) : object 'tau1' not found
```

This approach can work in shiny app without problem though, since the slider values will be available when the expression was evaluated. So right now I just use this method in my app, and the existing manipulate code also works.

**Comment by xhdong-umd** [comment]
I have finished the shiny app part code using abstracted functions. It's much more cleaner and will work for all future ctmm updates. I also moved the zoom slider to another location to make it clear it's different from other control sliders. The center slider button will not center error slider if it's with value 0, but center it when it have non-zero value.

![Uploading Screen Shot 2017-09-20 at 7.34.45 PM.png…]()

For the ctmm part, I put my edits in branch `variogram-fit`. The only real change is I added the zoom slider log base `b` to parameter. I also tried to use `do.call` in calling `storer` but always got error. I'm not sure how to make it work in manipulate expression. The current/original code is working so maybe we don't need to spend more time on it.

**Comment by xhdong-umd** [comment]
I tried again and made `do.call` worked with `storer`. I made another branch `variogram-fit2` so the changes are obvious for you (`variogram-fit` branch have several commits of failed attempts which make it difficult to see real difference).

**Comment by chfleming** [comment]
Did you still want to move `fraction(z)` from the backend to the manipulate front end, in which case you no longer need the `b=4` arguments?

**Comment by xhdong-umd** [comment]
I need the `b=4` not for fraction, but the min value of zoom slider, which is b based so I don't have to convert from 4 to 10. `fraction` itself is not needed for `storer`, and I'll pick the initial fraction value from the app page before the fine tune dialog, so the only thing I need were the min of zoom slider. 

If the min of zoom slider is not critical, I can just ignore all about fraction and zoom slider, so you don't need to change anything about it, nor do I need the `b=4` argument.

**Comment by chfleming** [comment]
You said that you were using a different formula without the shift right? The minimum zoom level I use (IIRC) is just so that a minimum of 10 lags are in the plot.

**Comment by xhdong-umd** [comment]
I just used 10 as log base and without the shift of `1` (otherwise the max will look weird). If you think  it's OK to use a fixed min zoom value like 0.001 in the app, I can just use that.

**Comment by chfleming** [comment]
I haven't noticed this before, but I checked in the webapp and the minimum zoom isn't as I would intend. My aim is that when zoomed all the way in, there's still some informative amount of data to see, 10 lags being an arbitrary choice. So if the zoom-fraction formulas are different, then the minimum zoom will be different too. 

E.g., if `fraction = 10^zoom`, and `min.fraction = 10*lag[2]/lag[n]`, where the 10 here is a somewhat arbitrary choice of at least `10` lags displayed when zoomed all the way in, then `min.zoom = log10(min.fraction)` or `min.zoom=log10(10*lag[2]/lag[n])` or `min.zoom=log10(lag[2]/lag[n])+1`.

**Comment by xhdong-umd** [comment]
I haven't update the webapp yet, my current code just use `b=10`, then use `min-1` from `backend`, which is just `log10(10*lag[2]/lag[n])`. I think this should be what you intended when base is 10.

Do you also want to change the min of zoom slider in group variogram page? that will need to consider multiple variograms though.

**Comment by chfleming** [comment]
Ah, ok.

For zooming all at once on the group page, I suppose I would use the smallest minimum.

**Comment by xhdong-umd** [comment]
So the current setting is fine, but that means I'll need the `b` argument from backend (but I don't need anything special about fraction).

**Comment by xhdong-umd** [comment]
For the group page, the slider was shared by relative and absolute views. The absolute slider just take a fraction of max y axis. I think the calculated 10 * lag will not apply in absolute mode, so it's difficult to change the slider min in this page.

**Comment by chfleming** [comment]
Ok, merged. Everything seems to be working great.

**Comment by xhdong-umd** [comment]
Thanks! I tested and it's working well. I updated the repo and the webapp.

One thing I'm not sure is about the error slider. I assume it will work properly since everything is handled by the ctmm backend function. 

Another question is about the user input of UERE in speed outlier page #28. Currently that input is only used to calculate speed outlier. Should that also change something in data, like setting `CTMM$error = TRUE`? or should it also change some error value?

**Comment by xhdong-umd** [comment]
@chfleming @jmcalabrese I'm looking at the pros and cons of different approaches refactoring the model selection page:

#### split into 2 pages
- The UI is cleaner. However it's not as easy as before to compare the guesstimate and model mode. Previously all 3 modes are in same location of UI, so switching modes make it easy to spot on differences. 
- We will need another plot control box in 2nd page, and to make the two plot control synchronized will need some additional complex code -- I need to link two controls to one set of global variables, and keep record of which control was updated more recently.
- It's also possible for user to click the 2nd page before the variogram page, since not all pages are needed in a workflow, so it's not obvious that user need to look at variogram before model page.

####  use 3 tabs
- I can put number in tab title to hint the proper order of usage: 1. Empirical 2. Guesstimate 3. Modeled
- The `try models` button should go to the 3rd tab, so usually user should click through 3 tabs and only fit models in last. Right now it's possible to click the button and jump to modeled mode (it will be still possible to switch to model tab directly, but less likely with 3 tabs).

**Comment by xhdong-umd** [comment]
I jus finished the changes on model selection page.

The 3 tabs are numbered with icons, this should provide some hint for user to check them in order (previously user can click `try models` without checking guess, now it's less likely for user to skip tab 2 and jump to tab 3).

<img width="740" alt="screen shot 2018-03-15 at 11 16 49 am" src="https://user-images.githubusercontent.com/25039897/37473371-9e028a9c-2844-11e8-9fae-a39c4396793f.png">

<img width="741" alt="screen shot 2018-03-15 at 11 17 00 am" src="https://user-images.githubusercontent.com/25039897/37473379-a23ffaea-2844-11e8-949f-8e296b86bc8b.png">

<img width="702" alt="screen shot 2018-03-15 at 11 30 24 am" src="https://user-images.githubusercontent.com/25039897/37473409-a94b00d2-2844-11e8-903f-a83b01a8731b.png">


I also moved the model selection table into the 3rd tab since it's only valid in modeled mode.

<img width="705" alt="screen shot 2018-03-15 at 11 30 33 am" src="https://user-images.githubusercontent.com/25039897/37473565-c5499c3a-2844-11e8-8fe2-701f189f7adb.png">


This arrangement should not have the random bug I meet before about the complex reactive values.
